"""Regression checks for trusted CI and release dependency inputs."""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

try:  # Python 3.11+
    import tomllib
except ModuleNotFoundError:  # Python 3.10 is still a supported CI target.
    import tomli as tomllib

from ops import render_project_status

ROOT = Path(__file__).parents[1]
CI = ROOT / ".github" / "workflows" / "ci.yml"
RELEASE = ROOT / ".github" / "workflows" / "release.yml"
WINDOWS = ROOT / ".github" / "workflows" / "windows.yml"
ACTION_SMOKE = ROOT / ".github" / "workflows" / "action-resolver-free-smoke.yml"
CODEQL = ROOT / ".github" / "workflows" / "codeql.yml"
SCORECARD = ROOT / ".github" / "workflows" / "scorecard.yml"
SOURCE_REVERIFY = ROOT / ".github" / "workflows" / "evoguard-release-source-reverify.yml"
SOURCE_RECEIPT = ROOT / ".github" / "workflows" / "evoguard-produce-release-source-receipt.yml"
BUILD_RELEASE = ROOT / ".github" / "workflows" / "evoguard-build-release-artifact.yml"
PYPROJECT = ROOT / "pyproject.toml"
CI_INPUT = ROOT / "requirements" / "ci.in"
CI_LOCK = ROOT / "requirements" / "ci.lock"
PYTHON310_COMPAT_INPUT = ROOT / "requirements" / "python310-compat.in"
PYTHON310_COMPAT_LOCK = ROOT / "requirements" / "python310-compat.lock"
DOCKER_INPUT = ROOT / "requirements" / "docker-pytest.in"
DOCKER_LOCK = ROOT / "requirements" / "docker-pytest.lock"
NODE_PACKAGE = ROOT / "tools" / "ci-vitest" / "package.json"
NODE_LOCK = ROOT / "tools" / "ci-vitest" / "package-lock.json"
LIVE_RUNNER = ROOT / ".github" / "workflows" / "runner-live-conformance.yml"
EXTENDED_NODE_PACKAGE = ROOT / "tools" / "ci-live-runners" / "node" / "package.json"
EXTENDED_NODE_LOCK = ROOT / "tools" / "ci-live-runners" / "node" / "package-lock.json"
EXTENDED_GO_MOD = ROOT / "tools" / "ci-live-runners" / "go" / "go.mod"
EXTENDED_GO_SUM = ROOT / "tools" / "ci-live-runners" / "go" / "go.sum"
EXTENDED_GEMFILE = ROOT / "tools" / "ci-live-runners" / "ruby" / "Gemfile"
EXTENDED_GEM_LOCK = ROOT / "tools" / "ci-live-runners" / "ruby" / "Gemfile.lock"
EXTENDED_MAVEN_POM = ROOT / "tools" / "ci-live-runners" / "maven" / "pom.xml"
EXTENDED_MAVEN_ARTIFACTS = (
    ROOT / "tools" / "ci-live-runners" / "maven" / "artifacts.sha256"
)
DOCKERFILE = ROOT / "ops" / "ci" / "docker" / "evoguard-e2e-pytest.Dockerfile"
POLICY = ROOT / "docs" / "DEPENDENCY_POLICY.md"
RUNNER_CONFORMANCE_POLICY = ROOT / "docs" / "RUNNER_CONFORMANCE.md"
THIRD_PARTY = ROOT / "THIRD_PARTY.md"
CODEOWNERS = ROOT / ".github" / "CODEOWNERS"
DEPENDABOT = ROOT / ".github" / "dependabot.yml"
GITIGNORE = ROOT / ".gitignore"


def _input_requirements(path: Path) -> list[str]:
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]


def _assert_hash_locked(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    assert "--generate-hashes" in text
    entries = re.split(r"(?=^[A-Za-z0-9_.-]+==)", text, flags=re.MULTILINE)
    locked = [entry for entry in entries if re.match(r"^[A-Za-z0-9_.-]+==", entry)]
    assert locked, f"{path.relative_to(ROOT)} has no resolved packages"
    for entry in locked:
        name = entry.split("==", 1)[0]
        assert re.search(r"^\s+--hash=sha256:[0-9a-f]{64}", entry, re.MULTILINE), (
            f"{path.relative_to(ROOT)} entry for {name} is not hash locked"
        )


def test_ci_source_declarations_match_pyproject_tooling() -> None:
    project = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))
    expected = [
        *project["build-system"]["requires"],
        "tomli==2.4.1",
        *project["project"]["optional-dependencies"]["dev"],
    ]
    assert _input_requirements(CI_INPUT) == expected


def test_python_locks_are_complete_hash_locks() -> None:
    ci = CI_LOCK.read_text(encoding="utf-8")
    assert "autogenerated by pip-compile with Python 3.10" in ci
    assert "--allow-unsafe" in ci
    _assert_hash_locked(CI_LOCK)
    tomli_block = ci.split("tomli==2.4.1", 1)[1].split("typing-extensions==", 1)[0]
    assert "#   -r requirements/ci.in" in tomli_block
    _assert_hash_locked(PYTHON310_COMPAT_LOCK)
    _assert_hash_locked(DOCKER_LOCK)
    assert _input_requirements(PYTHON310_COMPAT_INPUT) == [
        "importlib-resources==6.5.2"
    ]
    assert _input_requirements(DOCKER_INPUT) == ["pytest==9.1.1"]
    assert "pytest==9.1.1" in DOCKER_LOCK.read_text(encoding="utf-8")


def test_compatibility_backport_is_not_partially_updated_by_dependabot() -> None:
    text = DEPENDABOT.read_text(encoding="utf-8")
    pip_update = text.split("- package-ecosystem: pip", 1)[1]

    assert "dependency-name: importlib-resources" in pip_update
    assert "ignore:" in pip_update


def test_node_ci_lock_is_exact_and_integrity_bound() -> None:
    package = json.loads(NODE_PACKAGE.read_text(encoding="utf-8"))
    lock = json.loads(NODE_LOCK.read_text(encoding="utf-8"))
    assert package["devDependencies"] == {"vitest": "4.1.10"}
    assert lock["lockfileVersion"] == 3
    assert lock["packages"]["node_modules/vitest"]["version"] == "4.1.10"
    package_entries = {
        path: metadata for path, metadata in lock["packages"].items() if path.startswith("node_modules/")
    }
    assert package_entries
    assert all(metadata.get("integrity", "").startswith("sha512-") for metadata in package_entries.values())


def test_extended_node_lock_is_exact_and_integrity_bound() -> None:
    package = json.loads(EXTENDED_NODE_PACKAGE.read_text(encoding="utf-8"))
    lock = json.loads(EXTENDED_NODE_LOCK.read_text(encoding="utf-8"))
    expected = {
        "jest": "30.5.1",
        "jest-junit": "17.0.0",
        "mocha": "12.0.0",
    }

    assert package["private"] is True
    assert package["devDependencies"] == expected
    assert lock["lockfileVersion"] == 3
    assert lock["packages"][""]["devDependencies"] == expected
    for name, version in expected.items():
        assert lock["packages"][f"node_modules/{name}"]["version"] == version

    package_entries = {
        path: metadata
        for path, metadata in lock["packages"].items()
        if path.startswith("node_modules/")
    }
    assert len(package_entries) >= 3
    assert all(
        metadata.get("integrity", "").startswith("sha512-")
        for metadata in package_entries.values()
    )


def test_extended_go_and_ruby_locks_bind_exact_tool_graphs() -> None:
    assert EXTENDED_GO_MOD.read_text(encoding="utf-8").splitlines() == [
        "module github.com/EvoRiseKsa/EvoOM-Guard-m/tools/ci-live-runners/go",
        "",
        "go 1.27.1",
        "",
        "require gotest.tools/gotestsum v1.13.0",
    ]
    go_sum_lines = EXTENDED_GO_SUM.read_text(encoding="utf-8").splitlines()
    assert go_sum_lines == sorted(set(go_sum_lines))
    assert all(
        re.fullmatch(r"[^\s]+ [^\s]+(?:/go\.mod)? h1:[A-Za-z0-9+/]{43}=", line)
        for line in go_sum_lines
    )
    assert "gotest.tools/gotestsum v1.13.0 h1:+Lh454O9mu9AMG1APV4o0y7oDYKyik/3kBOiCqiEpRo=" in go_sum_lines
    assert "gotest.tools/gotestsum v1.13.0/go.mod h1:7f0NS5hFb0dWr4NtcsAsF0y1kzjEFfAil0HiBQJE03Q=" in go_sum_lines

    assert EXTENDED_GEMFILE.read_text(encoding="utf-8").splitlines() == [
        'source "https://rubygems.org"',
        "",
        'gem "rspec", "3.13.2"',
        'gem "rspec_junit_formatter", "0.6.0"',
    ]
    gem_lock = EXTENDED_GEM_LOCK.read_text(encoding="utf-8")
    gem_section = gem_lock.split("GEM\n", 1)[1].split("\nPLATFORMS", 1)[0]
    checksum_section = gem_lock.split("CHECKSUMS\n", 1)[1].split(
        "\nBUNDLED WITH", 1
    )[0]
    specs = set(
        re.findall(r"^    ([A-Za-z0-9_.-]+) \(([^)]+)\)$", gem_section, re.MULTILINE)
    )
    checksums = {
        (name, version): digest
        for name, version, digest in re.findall(
            r"^  ([A-Za-z0-9_.-]+) \(([^)]+)\) sha256=([0-9a-f]{64})$",
            checksum_section,
            re.MULTILINE,
        )
    }
    assert len(specs) == 7
    assert set(checksums) == specs
    assert ("rspec", "3.13.2") in specs
    assert ("rspec_junit_formatter", "0.6.0") in specs
    assert gem_lock.endswith("BUNDLED WITH\n   4.0.20\n")


def test_extended_maven_archive_and_repository_inventory_are_exact() -> None:
    pom = EXTENDED_MAVEN_POM.read_text(encoding="utf-8")
    assert pom.count("<junit.version>5.14.0</junit.version>") == 1
    assert pom.count("<artifactId>maven-compiler-plugin</artifactId>") == 1
    assert pom.count("<version>3.14.1</version>") == 1
    assert pom.count("<artifactId>maven-surefire-plugin</artifactId>") == 1
    assert pom.count("<version>3.5.6</version>") == 1
    assert pom.count("<maven.compiler.release>21</maven.compiler.release>") == 1
    bridge_default = (
        "<evoguard.surefire.reportsDirectory>"
        "${project.build.directory}/surefire-reports"
        "</evoguard.surefire.reportsDirectory>"
    )
    bridge_mapping = (
        "<reportsDirectory>"
        "${evoguard.surefire.reportsDirectory}"
        "</reportsDirectory>"
    )
    assert pom.count(bridge_default) == 1
    assert pom.count(bridge_mapping) == 1
    assert "/tools/ci-live-runners/maven/target/" in GITIGNORE.read_text(
        encoding="utf-8"
    ).splitlines()

    raw_manifest = EXTENDED_MAVEN_ARTIFACTS.read_bytes()
    assert hashlib.sha256(raw_manifest).hexdigest() == (
        "f37c00a195eda1587eec90849c385fe11438458fcb6a38e91dcba534e24ea18b"
    )
    assert raw_manifest.endswith(b"\n") and b"\r" not in raw_manifest
    lines = raw_manifest.decode("utf-8").removesuffix("\n").split("\n")
    assert len(lines) == 160
    matches = [
        re.fullmatch(r"([0-9a-f]{64})  ([A-Za-z0-9_.+/-]+\.(?:jar|pom))", line)
        for line in lines
    ]
    assert all(match is not None for match in matches)
    paths = [match.group(2) for match in matches if match is not None]
    assert paths == sorted(set(paths))


def test_extended_live_workflow_uses_the_reviewed_exact_inputs() -> None:
    text = LIVE_RUNNER.read_text(encoding="utf-8")
    expected_fragments = (
        'python-version: "3.12.10"',
        'node-version: "22.23.2"',
        'go-version: "1.27.1"',
        'java-version: "21.0.9+10"',
        'ruby-version: "3.4.10"',
        'bundler: "4.0.20"',
        "npm ci --ignore-scripts --prefix tools/ci-live-runners/node",
        "go mod verify",
        "go install gotest.tools/gotestsum",
        'BUNDLE_FROZEN: "true"',
        "bundle install --jobs 4 --retry 3",
        "python -m tools.conformance.fetch_live_runner_maven_cache",
    )
    for fragment in expected_fragments:
        assert fragment in text

    maven_sha512 = (
        "ed41650d42485cfc243fad22158caf9cbb5dc408ce7a09ddb94dd42a019de929c"
        "a43065bfa450612cf12bf78b5cafa3884b96c090de326ff590448c933454af3"
    )
    assert text.count(maven_sha512) == 2
    assert text.count("apache-maven-3.9.16-bin.zip") >= 4
    assert text.count(
        "python -m tools.conformance.verify_live_runner_maven_cache"
    ) == 2
    extended = text.split("\n  extended:\n", 1)[1].split(
        "\n  runner-live-conformance:\n", 1
    )[0]
    maven_commands = [
        line.strip()
        for line in extended.splitlines()
        if line.strip().startswith("mvn ")
    ]
    assert maven_commands
    assert all(" -o " in command for command in maven_commands)
    assert 'GOTOOLCHAIN: local' in text
    assert "needs: [live, extended]" in text
    maven_oracle = (ROOT / "tests" / "test_maven_live_oracle.py").read_text(
        encoding="utf-8"
    )
    assert '["mvn", "-q", "-o", f"-Dmaven.repo.local={repository}", "test"]' in (
        maven_oracle
    )


def test_workflows_install_only_from_locked_inputs() -> None:
    workflows = (CI, RELEASE, WINDOWS, ACTION_SMOKE)
    text = "\n".join(path.read_text(encoding="utf-8") for path in workflows)
    assert "npm install -g" not in text
    assert text.count("npm ci --ignore-scripts --prefix tools/ci-vitest") == 4

    pip_commands = re.findall(r"^\s*python -m pip install (?P<args>[^\n]+)$", text, flags=re.MULTILINE)
    assert pip_commands
    for args in pip_commands:
        assert (
            args == "--only-binary=:all: --require-hashes -r requirements/ci.lock"
            or args
            == (
                "--only-binary=:all: --require-hashes "
                "-r requirements/python310-compat.lock"
            )
            or args == "--no-deps --no-build-isolation -e ."
            or args
            == (
                "--only-binary=:all: --require-hashes "
                "-r .venv/action-source/requirements/docker-pytest.lock"
            )
            or args
            == (
                "--only-binary=:all: --require-hashes "
                "-r .venv/action-source/requirements/ci.lock"
            )
        ), f"unlocked workflow pip command: {args!r}"
    pip_uninstalls = re.findall(
        r"^\s*python -m pip uninstall (?P<args>[^\n]+)$",
        text,
        flags=re.MULTILINE,
    )
    assert pip_uninstalls == ["-y coverage"]

    for workflow in (CI, RELEASE):
        workflow_text = workflow.read_text(encoding="utf-8")
        assert "docker build --build-arg PYTHON_IMAGE=\"$EVOGUARD_E2E_IMAGE\"" in workflow_text
        assert "docker pull \"$EVOGUARD_E2E_IMAGE\"" in workflow_text


def test_docker_base_is_digest_pinned_everywhere() -> None:
    dockerfile = DOCKERFILE.read_text(encoding="utf-8")
    match = re.search(
        r"ARG PYTHON_IMAGE=(python:3\.12-slim@sha256:[0-9a-f]{64})$", dockerfile, re.MULTILINE
    )
    assert match is not None
    image = match.group(1)
    assert "FROM ${PYTHON_IMAGE}" in dockerfile
    assert "--only-binary=:all: --require-hashes -r /tmp/docker-pytest.lock" in dockerfile
    for workflow in (CI, RELEASE):
        assert f"EVOGUARD_E2E_IMAGE: {image}" in workflow.read_text(encoding="utf-8")


def test_product_and_consumer_boundaries_are_documented() -> None:
    project = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))
    assert project["project"]["dependencies"] == []
    policy = POLICY.read_text(encoding="utf-8")
    assert "github.action_path" in policy
    assert "resolver-free **bootstrap**, not a zero-network Action" in policy
    assert "OpenSSF Scorecard" in policy


def test_extended_runner_locks_and_claim_boundary_are_documented() -> None:
    dependency_policy = POLICY.read_text(encoding="utf-8")
    runner_policy = RUNNER_CONFORMANCE_POLICY.read_text(encoding="utf-8")
    runner_words = " ".join(runner_policy.split())
    third_party = THIRD_PARTY.read_text(encoding="utf-8")

    for value in (
        "Python 3.12.10",
        "Node 22.23.2",
        "Go 1.27.1",
        "Ruby 3.4.10",
        "Bundler 4.0.20",
        "Temurin 21.0.9+10",
        "Maven 3.9.16",
        "160 JAR/POM",
        "evoguard.surefire.reportsDirectory",
        "f37c00a195eda1587eec90849c385fe11438458fcb6a38e91dcba534e24ea18b",
        "before any Maven plugin or downloaded JAR executes",
        "not a network sandbox",
    ):
        assert value in dependency_policy

    assert "checked-in configuration is not itself evidence" in runner_words
    assert "same-owner GitHub-hosted operational conformance evidence" in runner_words
    assert "not an independent evaluation" in runner_words
    assert "hostile code production isolation" in runner_words
    assert "Core GA or Enterprise readiness" in runner_words
    assert "Maven live conformance is an explicit project opt-in" in runner_words
    assert "Without it, no judge-owned report" in runner_words
    assert "generic Maven-project support claim" in runner_words
    for path in (
        "tools/ci-live-runners/node/",
        "tools/ci-live-runners/go/",
        "tools/ci-live-runners/ruby/",
        "tools/ci-live-runners/maven/",
    ):
        assert path in third_party


def test_action_smoke_exercises_only_reviewed_locked_environments() -> None:
    text = ACTION_SMOKE.read_text(encoding="utf-8")
    assert "requirements/docker-pytest.lock" in text
    assert "requirements/ci.lock" in text
    assert 'PIP_NO_INDEX: "1"' in text
    assert 'PIP_REQUIRE_VIRTUALENV: "1"' in text
    assert "core-no-coverage" in text
    assert "advisory-coverage-missing" in text
    assert "required-coverage-missing" in text
    assert "required-coverage-available" in text


def test_action_smoke_neutralizes_host_git_credential_helpers() -> None:
    text = ACTION_SMOKE.read_text(encoding="utf-8")
    boundary = text.index("Create a candidate-safe Git configuration boundary")
    action = text.index("Run the local composite Action")
    assert boundary < action
    assert 'SAFE_GIT_CONFIG="$RUNNER_TEMP/evoguard-empty-global.gitconfig"' in text
    assert 'GIT_CONFIG_NOSYSTEM: "1"' in text
    assert "GIT_CONFIG_GLOBAL: ${{ steps.candidate-git.outputs.global-config }}" in text
    assert 'GIT_TERMINAL_PROMPT: "0"' in text


def test_reviewed_github_action_update_pins_are_exact() -> None:
    checkout = "3d3c42e5aac5ba805825da76410c181273ba90b1"
    attest = "1e69f48acb82d1966a394da916b4c1698aa569d6"
    codeql = "cdf488f595d80d6e07e03d4674febd5ab45fa938"

    source_reverify = SOURCE_REVERIFY.read_text(encoding="utf-8")
    source_receipt = SOURCE_RECEIPT.read_text(encoding="utf-8")
    build_release = BUILD_RELEASE.read_text(encoding="utf-8")
    codeql_workflow = CODEQL.read_text(encoding="utf-8")
    scorecard = SCORECARD.read_text(encoding="utf-8")

    assert source_reverify.count(f"actions/checkout@{checkout}") == 3
    assert source_receipt.count(f"actions/attest@{attest}") == 1
    assert build_release.count(f"actions/attest@{attest}") == 3
    assert codeql_workflow.count(f"github/codeql-action/init@{codeql}") == 1
    assert codeql_workflow.count(f"github/codeql-action/analyze@{codeql}") == 1
    assert scorecard.count(f"github/codeql-action/upload-sarif@{codeql}") == 1


def test_published_release_record_retains_its_historical_workflow_pin() -> None:
    historical_attest = "508db95dd578ae2727ebd6217d5ba78e4fbda05d"
    reviewed_attest = "1e69f48acb82d1966a394da916b4c1698aa569d6"
    source_commit = "b222c7df0a3eaef6e89287cd1354625b88ac8b8b"
    workflow_path = ".github/workflows/release.yml"
    workflow_blob_sha = "ac995a85193c44f3736ee07af7562ae0b28c68fc"
    workflow_sha256 = (
        "840ad7257e82fdcccdf751fe6b55aaad8a58679c3e39825cb0d1628e0fda1769"
    )
    verifier_path = ".github/workflows/release-published-verify.yml"
    verifier_blob_sha = "67e95bae6c650a2e3606a24fae0967bab649b7d5"
    verifier_sha256 = (
        "20f9f759bd9f14ae16e697894d62e6eb0eb82d6a26333d41a025cbbb81ea4478"
    )
    record = json.loads(
        (ROOT / "evidence/direct-releases/v4.7.1/DIRECT_RELEASE.json").read_text(
            encoding="utf-8"
        )
    )
    workflow = record["workflow"]
    assert record["source"]["commit_sha"] == source_commit
    assert workflow["workflow_path"] == workflow_path
    assert workflow["workflow_blob_sha"] == workflow_blob_sha
    assert workflow["workflow_sha256"] == workflow_sha256
    assert workflow["verifier_path"] == verifier_path
    assert workflow["verifier_blob_sha"] == verifier_blob_sha
    assert workflow["verifier_sha256"] == verifier_sha256
    assert render_project_status._DIRECT_RELEASE_WORKFLOW_CONTRACTS["4.7.1"] == (
        workflow_path,
        workflow_sha256,
        verifier_path,
        verifier_sha256,
    )
    with render_project_status._trusted_git_session(ROOT):
        release = render_project_status._git_bytes(
            ROOT,
            "show",
            "--end-of-options",
            f"{source_commit}:{workflow_path}",
        )

    assert hashlib.sha256(release).hexdigest() == workflow_sha256
    header = f"blob {len(release)}\0".encode("ascii")
    assert (
        hashlib.sha1(header + release, usedforsecurity=False).hexdigest()
        == workflow_blob_sha
    )
    text = release.decode("utf-8", "strict")
    assert text.count(f"actions/attest@{historical_attest}") == 2
    assert f"actions/attest@{reviewed_attest}" not in text


def test_v480_direct_record_pins_its_release_history_and_nonclaims() -> None:
    source_commit = "07e361cb9a75cc1822cd905ca65df42235b3b910"
    workflow_path = ".github/workflows/release.yml"
    workflow_blob_sha = "dc24c9ff17cc55ddf689dc0dc2dd61a568117d72"
    workflow_sha256 = (
        "c1a404466c4bc98e98f43113fb636ac838bd7130726fe027cc5dc9eb8294b026"
    )
    verifier_path = ".github/workflows/release-published-verify.yml"
    verifier_blob_sha = "67e95bae6c650a2e3606a24fae0967bab649b7d5"
    verifier_sha256 = (
        "20f9f759bd9f14ae16e697894d62e6eb0eb82d6a26333d41a025cbbb81ea4478"
    )
    record = json.loads(
        (ROOT / "evidence/direct-releases/v4.8.0/DIRECT_RELEASE.json").read_text(
            encoding="utf-8"
        )
    )
    workflow = record["workflow"]
    assert record["source"]["commit_sha"] == source_commit
    assert workflow["workflow_blob_sha"] == workflow_blob_sha
    assert workflow["verifier_blob_sha"] == verifier_blob_sha
    assert render_project_status._DIRECT_RELEASE_WORKFLOW_CONTRACTS["4.8.0"] == (
        workflow_path,
        workflow_sha256,
        verifier_path,
        verifier_sha256,
    )
    assert render_project_status._DIRECT_RELEASE_HISTORY_CONTRACTS["4.8.0"] == (
        "evidence/release-ledgers/v4.6.0/RELEASE_LEDGER.json"
    )
    assert tuple(record["trust_boundary"]["non_claims"]) == (
        render_project_status._DIRECT_RELEASE_NON_CLAIM_CONTRACTS["4.8.0"]
    )

    with render_project_status._trusted_git_session(ROOT):
        release = render_project_status._git_bytes(
            ROOT,
            "show",
            "--end-of-options",
            f"{source_commit}:{workflow_path}",
        )
        verifier = render_project_status._git_bytes(
            ROOT,
            "show",
            "--end-of-options",
            f"{source_commit}:{verifier_path}",
        )
    assert hashlib.sha256(release).hexdigest() == workflow_sha256
    assert hashlib.sha256(verifier).hexdigest() == verifier_sha256
    assert hashlib.sha1(
        f"blob {len(release)}\0".encode("ascii") + release,
        usedforsecurity=False,
    ).hexdigest() == workflow_blob_sha
    assert hashlib.sha1(
        f"blob {len(verifier)}\0".encode("ascii") + verifier,
        usedforsecurity=False,
    ).hexdigest() == verifier_blob_sha


def test_v481_direct_record_pins_its_release_history_and_nonclaims() -> None:
    source_commit = "e63e9d806fef38c9dfd3bfb1a0bc1b2d12c58ac8"
    workflow_path = ".github/workflows/release.yml"
    workflow_blob_sha = "dc24c9ff17cc55ddf689dc0dc2dd61a568117d72"
    workflow_sha256 = (
        "c1a404466c4bc98e98f43113fb636ac838bd7130726fe027cc5dc9eb8294b026"
    )
    verifier_path = ".github/workflows/release-published-verify.yml"
    verifier_blob_sha = "67e95bae6c650a2e3606a24fae0967bab649b7d5"
    verifier_sha256 = (
        "20f9f759bd9f14ae16e697894d62e6eb0eb82d6a26333d41a025cbbb81ea4478"
    )
    record = json.loads(
        (ROOT / "evidence/direct-releases/v4.8.1/DIRECT_RELEASE.json").read_text(
            encoding="utf-8"
        )
    )
    workflow = record["workflow"]
    assert record["source"]["commit_sha"] == source_commit
    assert workflow["workflow_blob_sha"] == workflow_blob_sha
    assert workflow["verifier_blob_sha"] == verifier_blob_sha
    assert render_project_status._DIRECT_RELEASE_WORKFLOW_CONTRACTS["4.8.1"] == (
        workflow_path,
        workflow_sha256,
        verifier_path,
        verifier_sha256,
    )
    assert render_project_status._DIRECT_RELEASE_HISTORY_CONTRACTS["4.8.1"] == (
        "evidence/release-ledgers/v4.6.0/RELEASE_LEDGER.json"
    )
    assert record["release"]["created_utc_semantics"] == (
        render_project_status._DIRECT_RELEASE_CREATED_UTC_SEMANTICS_CONTRACTS[
            "4.8.1"
        ]
    )
    assert tuple(record["trust_boundary"]["non_claims"]) == (
        render_project_status._DIRECT_RELEASE_NON_CLAIM_CONTRACTS["4.8.1"]
    )

    with render_project_status._trusted_git_session(ROOT):
        release = render_project_status._git_bytes(
            ROOT,
            "show",
            "--end-of-options",
            f"{source_commit}:{workflow_path}",
        )
        verifier = render_project_status._git_bytes(
            ROOT,
            "show",
            "--end-of-options",
            f"{source_commit}:{verifier_path}",
        )
    assert hashlib.sha256(release).hexdigest() == workflow_sha256
    assert hashlib.sha256(verifier).hexdigest() == verifier_sha256
    assert hashlib.sha1(
        f"blob {len(release)}\0".encode("ascii") + release,
        usedforsecurity=False,
    ).hexdigest() == workflow_blob_sha
    assert hashlib.sha1(
        f"blob {len(verifier)}\0".encode("ascii") + verifier,
        usedforsecurity=False,
    ).hexdigest() == verifier_blob_sha


def test_trusted_dependency_inputs_are_codeowner_protected() -> None:
    codeowners = CODEOWNERS.read_text(encoding="utf-8")
    for path in (
        "/requirements/",
        "/tools/ci-vitest/",
        "/tools/ci-live-runners/",
        "/tools/conformance/",
        "/ops/ci/",
        "/ops/build_pyz.py",
        "/ops/generate_spdx_sbom.py",
        "/tests/test_action_security.py",
        "/tests/test_adapters.py",
        "/tests/test_adversarial_integrity_boundaries.py",
        "/tests/test_dependency_lock_policy.py",
        "/tests/test_junit_hardening.py",
        "/tests/test_repo_phase_characterization.py",
        "/tests/conformance/",
        "/tests/live_runner_extended_helpers.py",
        "/tests/test_*_live_oracle.py",
        "/tests/test_live_runner_maven_cache.py",
        "/tests/test_release_security.py",
        "/tests/test_spdx_sbom.py",
        "/tests/schema/",
        "/tests/test_zipapp.py",
        "/docs/DEPENDENCY_POLICY.md",
        "/docs/EVIDENCE_BUNDLES.md",
        "/docs/GUARD.md",
        "/docs/RUNNER_CONFORMANCE.md",
        "/docs/SBOM.md",
        "/THIRD_PARTY.md",
        "/evidence/direct-releases/",
    ):
        assert f"{path} @MANA-awam" in codeowners
