"""Regression checks for trusted CI and release dependency inputs."""

from __future__ import annotations

import json
import re
from pathlib import Path

try:  # Python 3.11+
    import tomllib
except ModuleNotFoundError:  # Python 3.10 is still a supported CI target.
    import tomli as tomllib

ROOT = Path(__file__).parents[1]
CI = ROOT / ".github" / "workflows" / "ci.yml"
RELEASE = ROOT / ".github" / "workflows" / "release.yml"
WINDOWS = ROOT / ".github" / "workflows" / "windows.yml"
ACTION_SMOKE = ROOT / ".github" / "workflows" / "action-resolver-free-smoke.yml"
PYPROJECT = ROOT / "pyproject.toml"
CI_INPUT = ROOT / "requirements" / "ci.in"
CI_LOCK = ROOT / "requirements" / "ci.lock"
DOCKER_INPUT = ROOT / "requirements" / "docker-pytest.in"
DOCKER_LOCK = ROOT / "requirements" / "docker-pytest.lock"
NODE_PACKAGE = ROOT / "tools" / "ci-vitest" / "package.json"
NODE_LOCK = ROOT / "tools" / "ci-vitest" / "package-lock.json"
DOCKERFILE = ROOT / "ops" / "ci" / "docker" / "evoguard-e2e-pytest.Dockerfile"
POLICY = ROOT / "docs" / "DEPENDENCY_POLICY.md"
CODEOWNERS = ROOT / ".github" / "CODEOWNERS"


def _input_requirements(path: Path) -> list[str]:
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]


def _assert_hash_locked(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    assert "--generate-hashes" in text
    entries = re.split(r"(?=^[A-Za-z0-9_.-]+==)", text, flags=re.MULTILINE)
    locked = [entry for entry in entries if re.match(r"^[A-Za-z0-9_.-]+==", entry)]
    assert locked, f"{path.relative_to(ROOT)} has no resolved packages"
    for entry in locked:
        name = entry.split("==", 1)[0]
        assert re.search(r"^\s+--hash=sha256:[0-9a-f]{64}", entry, re.MULTILINE), (
            f"{path.relative_to(ROOT)} entry for {name} is not hash locked"
        )


def test_ci_source_declarations_match_pyproject_tooling() -> None:
    project = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))
    expected = [
        *project["build-system"]["requires"],
        *project["project"]["optional-dependencies"]["dev"],
    ]
    assert _input_requirements(CI_INPUT) == expected


def test_python_locks_are_complete_hash_locks() -> None:
    ci = CI_LOCK.read_text(encoding="utf-8")
    assert "autogenerated by pip-compile with Python 3.10" in ci
    assert "--allow-unsafe" in ci
    _assert_hash_locked(CI_LOCK)
    _assert_hash_locked(DOCKER_LOCK)
    assert _input_requirements(DOCKER_INPUT) == ["pytest==9.1.1"]
    assert "pytest==9.1.1" in DOCKER_LOCK.read_text(encoding="utf-8")


def test_node_ci_lock_is_exact_and_integrity_bound() -> None:
    package = json.loads(NODE_PACKAGE.read_text(encoding="utf-8"))
    lock = json.loads(NODE_LOCK.read_text(encoding="utf-8"))
    assert package["devDependencies"] == {"vitest": "4.1.10"}
    assert lock["lockfileVersion"] == 3
    assert lock["packages"]["node_modules/vitest"]["version"] == "4.1.10"
    package_entries = {
        path: metadata for path, metadata in lock["packages"].items() if path.startswith("node_modules/")
    }
    assert package_entries
    assert all(metadata.get("integrity", "").startswith("sha512-") for metadata in package_entries.values())


def test_workflows_install_only_from_locked_inputs() -> None:
    workflows = (CI, RELEASE, WINDOWS, ACTION_SMOKE)
    text = "\n".join(path.read_text(encoding="utf-8") for path in workflows)
    assert "npm install -g" not in text
    assert text.count("npm ci --ignore-scripts --prefix tools/ci-vitest") == 4

    pip_commands = re.findall(r"^\s*python -m pip install (?P<args>[^\n]+)$", text, flags=re.MULTILINE)
    assert pip_commands
    for args in pip_commands:
        assert (
            args == "--only-binary=:all: --require-hashes -r requirements/ci.lock"
            or args == "--no-deps --no-build-isolation -e ."
            or args
            == (
                "--only-binary=:all: --require-hashes "
                "-r .venv/action-source/requirements/docker-pytest.lock"
            )
            or args
            == (
                "--only-binary=:all: --require-hashes "
                "-r .venv/action-source/requirements/ci.lock"
            )
        ), f"unlocked workflow pip command: {args!r}"
    pip_uninstalls = re.findall(
        r"^\s*python -m pip uninstall (?P<args>[^\n]+)$",
        text,
        flags=re.MULTILINE,
    )
    assert pip_uninstalls == ["-y coverage"]

    for workflow in (CI, RELEASE):
        workflow_text = workflow.read_text(encoding="utf-8")
        assert "docker build --build-arg PYTHON_IMAGE=\"$EVOGUARD_E2E_IMAGE\"" in workflow_text
        assert "docker pull \"$EVOGUARD_E2E_IMAGE\"" in workflow_text


def test_docker_base_is_digest_pinned_everywhere() -> None:
    dockerfile = DOCKERFILE.read_text(encoding="utf-8")
    match = re.search(
        r"ARG PYTHON_IMAGE=(python:3\.12-slim@sha256:[0-9a-f]{64})$", dockerfile, re.MULTILINE
    )
    assert match is not None
    image = match.group(1)
    assert "FROM ${PYTHON_IMAGE}" in dockerfile
    assert "--only-binary=:all: --require-hashes -r /tmp/docker-pytest.lock" in dockerfile
    for workflow in (CI, RELEASE):
        assert f"EVOGUARD_E2E_IMAGE: {image}" in workflow.read_text(encoding="utf-8")


def test_product_and_consumer_boundaries_are_documented() -> None:
    project = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))
    assert project["project"]["dependencies"] == []
    policy = POLICY.read_text(encoding="utf-8")
    assert "github.action_path" in policy
    assert "resolver-free **bootstrap**, not a zero-network Action" in policy
    assert "OpenSSF Scorecard" in policy


def test_action_smoke_exercises_only_reviewed_locked_environments() -> None:
    text = ACTION_SMOKE.read_text(encoding="utf-8")
    assert "requirements/docker-pytest.lock" in text
    assert "requirements/ci.lock" in text
    assert 'PIP_NO_INDEX: "1"' in text
    assert 'PIP_REQUIRE_VIRTUALENV: "1"' in text
    assert "core-no-coverage" in text
    assert "advisory-coverage-missing" in text
    assert "required-coverage-missing" in text
    assert "required-coverage-available" in text


def test_trusted_dependency_inputs_are_codeowner_protected() -> None:
    codeowners = CODEOWNERS.read_text(encoding="utf-8")
    for path in (
        "/requirements/",
        "/tools/ci-vitest/",
        "/ops/ci/",
        "/ops/build_pyz.py",
        "/ops/generate_spdx_sbom.py",
        "/tests/test_action_security.py",
        "/tests/test_dependency_lock_policy.py",
        "/tests/test_release_security.py",
        "/tests/test_spdx_sbom.py",
        "/tests/schema/",
        "/tests/test_zipapp.py",
        "/docs/DEPENDENCY_POLICY.md",
        "/docs/EVIDENCE_BUNDLES.md",
        "/docs/GUARD.md",
        "/docs/SBOM.md",
    ):
        assert f"{path} @MANA-awam" in codeowners
