"""Regression checks for trusted CI and release dependency inputs."""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

try:  # Python 3.11+
    import tomllib
except ModuleNotFoundError:  # Python 3.10 is still a supported CI target.
    import tomli as tomllib

from ops import render_project_status

ROOT = Path(__file__).parents[1]
CI = ROOT / ".github" / "workflows" / "ci.yml"
RELEASE = ROOT / ".github" / "workflows" / "release.yml"
WINDOWS = ROOT / ".github" / "workflows" / "windows.yml"
ACTION_SMOKE = ROOT / ".github" / "workflows" / "action-resolver-free-smoke.yml"
CODEQL = ROOT / ".github" / "workflows" / "codeql.yml"
SCORECARD = ROOT / ".github" / "workflows" / "scorecard.yml"
SOURCE_REVERIFY = ROOT / ".github" / "workflows" / "evoguard-release-source-reverify.yml"
SOURCE_RECEIPT = ROOT / ".github" / "workflows" / "evoguard-produce-release-source-receipt.yml"
BUILD_RELEASE = ROOT / ".github" / "workflows" / "evoguard-build-release-artifact.yml"
PYPROJECT = ROOT / "pyproject.toml"
CI_INPUT = ROOT / "requirements" / "ci.in"
CI_LOCK = ROOT / "requirements" / "ci.lock"
PYTHON310_COMPAT_INPUT = ROOT / "requirements" / "python310-compat.in"
PYTHON310_COMPAT_LOCK = ROOT / "requirements" / "python310-compat.lock"
DOCKER_INPUT = ROOT / "requirements" / "docker-pytest.in"
DOCKER_LOCK = ROOT / "requirements" / "docker-pytest.lock"
NODE_PACKAGE = ROOT / "tools" / "ci-vitest" / "package.json"
NODE_LOCK = ROOT / "tools" / "ci-vitest" / "package-lock.json"
DOCKERFILE = ROOT / "ops" / "ci" / "docker" / "evoguard-e2e-pytest.Dockerfile"
POLICY = ROOT / "docs" / "DEPENDENCY_POLICY.md"
CODEOWNERS = ROOT / ".github" / "CODEOWNERS"
DEPENDABOT = ROOT / ".github" / "dependabot.yml"


def _input_requirements(path: Path) -> list[str]:
    return [
        line.strip()
        for line in path.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.lstrip().startswith("#")
    ]


def _assert_hash_locked(path: Path) -> None:
    text = path.read_text(encoding="utf-8")
    assert "--generate-hashes" in text
    entries = re.split(r"(?=^[A-Za-z0-9_.-]+==)", text, flags=re.MULTILINE)
    locked = [entry for entry in entries if re.match(r"^[A-Za-z0-9_.-]+==", entry)]
    assert locked, f"{path.relative_to(ROOT)} has no resolved packages"
    for entry in locked:
        name = entry.split("==", 1)[0]
        assert re.search(r"^\s+--hash=sha256:[0-9a-f]{64}", entry, re.MULTILINE), (
            f"{path.relative_to(ROOT)} entry for {name} is not hash locked"
        )


def test_ci_source_declarations_match_pyproject_tooling() -> None:
    project = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))
    expected = [
        *project["build-system"]["requires"],
        *project["project"]["optional-dependencies"]["dev"],
    ]
    assert _input_requirements(CI_INPUT) == expected


def test_python_locks_are_complete_hash_locks() -> None:
    ci = CI_LOCK.read_text(encoding="utf-8")
    assert "autogenerated by pip-compile with Python 3.10" in ci
    assert "--allow-unsafe" in ci
    _assert_hash_locked(CI_LOCK)
    _assert_hash_locked(PYTHON310_COMPAT_LOCK)
    _assert_hash_locked(DOCKER_LOCK)
    assert _input_requirements(PYTHON310_COMPAT_INPUT) == [
        "importlib-resources==6.5.2"
    ]
    assert _input_requirements(DOCKER_INPUT) == ["pytest==9.1.1"]
    assert "pytest==9.1.1" in DOCKER_LOCK.read_text(encoding="utf-8")


def test_compatibility_backport_is_not_partially_updated_by_dependabot() -> None:
    text = DEPENDABOT.read_text(encoding="utf-8")
    pip_update = text.split("- package-ecosystem: pip", 1)[1]

    assert "dependency-name: importlib-resources" in pip_update
    assert "ignore:" in pip_update


def test_node_ci_lock_is_exact_and_integrity_bound() -> None:
    package = json.loads(NODE_PACKAGE.read_text(encoding="utf-8"))
    lock = json.loads(NODE_LOCK.read_text(encoding="utf-8"))
    assert package["devDependencies"] == {"vitest": "4.1.10"}
    assert lock["lockfileVersion"] == 3
    assert lock["packages"]["node_modules/vitest"]["version"] == "4.1.10"
    package_entries = {
        path: metadata for path, metadata in lock["packages"].items() if path.startswith("node_modules/")
    }
    assert package_entries
    assert all(metadata.get("integrity", "").startswith("sha512-") for metadata in package_entries.values())


def test_workflows_install_only_from_locked_inputs() -> None:
    workflows = (CI, RELEASE, WINDOWS, ACTION_SMOKE)
    text = "\n".join(path.read_text(encoding="utf-8") for path in workflows)
    assert "npm install -g" not in text
    assert text.count("npm ci --ignore-scripts --prefix tools/ci-vitest") == 4

    pip_commands = re.findall(r"^\s*python -m pip install (?P<args>[^\n]+)$", text, flags=re.MULTILINE)
    assert pip_commands
    for args in pip_commands:
        assert (
            args == "--only-binary=:all: --require-hashes -r requirements/ci.lock"
            or args
            == (
                "--only-binary=:all: --require-hashes "
                "-r requirements/python310-compat.lock"
            )
            or args == "--no-deps --no-build-isolation -e ."
            or args
            == (
                "--only-binary=:all: --require-hashes "
                "-r .venv/action-source/requirements/docker-pytest.lock"
            )
            or args
            == (
                "--only-binary=:all: --require-hashes "
                "-r .venv/action-source/requirements/ci.lock"
            )
        ), f"unlocked workflow pip command: {args!r}"
    pip_uninstalls = re.findall(
        r"^\s*python -m pip uninstall (?P<args>[^\n]+)$",
        text,
        flags=re.MULTILINE,
    )
    assert pip_uninstalls == ["-y coverage"]

    for workflow in (CI, RELEASE):
        workflow_text = workflow.read_text(encoding="utf-8")
        assert "docker build --build-arg PYTHON_IMAGE=\"$EVOGUARD_E2E_IMAGE\"" in workflow_text
        assert "docker pull \"$EVOGUARD_E2E_IMAGE\"" in workflow_text


def test_docker_base_is_digest_pinned_everywhere() -> None:
    dockerfile = DOCKERFILE.read_text(encoding="utf-8")
    match = re.search(
        r"ARG PYTHON_IMAGE=(python:3\.12-slim@sha256:[0-9a-f]{64})$", dockerfile, re.MULTILINE
    )
    assert match is not None
    image = match.group(1)
    assert "FROM ${PYTHON_IMAGE}" in dockerfile
    assert "--only-binary=:all: --require-hashes -r /tmp/docker-pytest.lock" in dockerfile
    for workflow in (CI, RELEASE):
        assert f"EVOGUARD_E2E_IMAGE: {image}" in workflow.read_text(encoding="utf-8")


def test_product_and_consumer_boundaries_are_documented() -> None:
    project = tomllib.loads(PYPROJECT.read_text(encoding="utf-8"))
    assert project["project"]["dependencies"] == []
    policy = POLICY.read_text(encoding="utf-8")
    assert "github.action_path" in policy
    assert "resolver-free **bootstrap**, not a zero-network Action" in policy
    assert "OpenSSF Scorecard" in policy


def test_action_smoke_exercises_only_reviewed_locked_environments() -> None:
    text = ACTION_SMOKE.read_text(encoding="utf-8")
    assert "requirements/docker-pytest.lock" in text
    assert "requirements/ci.lock" in text
    assert 'PIP_NO_INDEX: "1"' in text
    assert 'PIP_REQUIRE_VIRTUALENV: "1"' in text
    assert "core-no-coverage" in text
    assert "advisory-coverage-missing" in text
    assert "required-coverage-missing" in text
    assert "required-coverage-available" in text


def test_action_smoke_neutralizes_host_git_credential_helpers() -> None:
    text = ACTION_SMOKE.read_text(encoding="utf-8")
    boundary = text.index("Create a candidate-safe Git configuration boundary")
    action = text.index("Run the local composite Action")
    assert boundary < action
    assert 'SAFE_GIT_CONFIG="$RUNNER_TEMP/evoguard-empty-global.gitconfig"' in text
    assert 'GIT_CONFIG_NOSYSTEM: "1"' in text
    assert "GIT_CONFIG_GLOBAL: ${{ steps.candidate-git.outputs.global-config }}" in text
    assert 'GIT_TERMINAL_PROMPT: "0"' in text


def test_reviewed_github_action_update_pins_are_exact() -> None:
    checkout = "3d3c42e5aac5ba805825da76410c181273ba90b1"
    attest = "1e69f48acb82d1966a394da916b4c1698aa569d6"
    codeql = "cdf488f595d80d6e07e03d4674febd5ab45fa938"

    source_reverify = SOURCE_REVERIFY.read_text(encoding="utf-8")
    source_receipt = SOURCE_RECEIPT.read_text(encoding="utf-8")
    build_release = BUILD_RELEASE.read_text(encoding="utf-8")
    codeql_workflow = CODEQL.read_text(encoding="utf-8")
    scorecard = SCORECARD.read_text(encoding="utf-8")

    assert source_reverify.count(f"actions/checkout@{checkout}") == 3
    assert source_receipt.count(f"actions/attest@{attest}") == 1
    assert build_release.count(f"actions/attest@{attest}") == 3
    assert codeql_workflow.count(f"github/codeql-action/init@{codeql}") == 1
    assert codeql_workflow.count(f"github/codeql-action/analyze@{codeql}") == 1
    assert scorecard.count(f"github/codeql-action/upload-sarif@{codeql}") == 1


def test_published_release_record_retains_its_historical_workflow_pin() -> None:
    historical_attest = "508db95dd578ae2727ebd6217d5ba78e4fbda05d"
    reviewed_attest = "1e69f48acb82d1966a394da916b4c1698aa569d6"
    source_commit = "b222c7df0a3eaef6e89287cd1354625b88ac8b8b"
    workflow_path = ".github/workflows/release.yml"
    workflow_blob_sha = "ac995a85193c44f3736ee07af7562ae0b28c68fc"
    workflow_sha256 = (
        "840ad7257e82fdcccdf751fe6b55aaad8a58679c3e39825cb0d1628e0fda1769"
    )
    verifier_path = ".github/workflows/release-published-verify.yml"
    verifier_blob_sha = "67e95bae6c650a2e3606a24fae0967bab649b7d5"
    verifier_sha256 = (
        "20f9f759bd9f14ae16e697894d62e6eb0eb82d6a26333d41a025cbbb81ea4478"
    )
    record = json.loads(
        (ROOT / "evidence/direct-releases/v4.7.1/DIRECT_RELEASE.json").read_text(
            encoding="utf-8"
        )
    )
    workflow = record["workflow"]
    assert record["source"]["commit_sha"] == source_commit
    assert workflow["workflow_path"] == workflow_path
    assert workflow["workflow_blob_sha"] == workflow_blob_sha
    assert workflow["workflow_sha256"] == workflow_sha256
    assert workflow["verifier_path"] == verifier_path
    assert workflow["verifier_blob_sha"] == verifier_blob_sha
    assert workflow["verifier_sha256"] == verifier_sha256
    assert render_project_status._DIRECT_RELEASE_WORKFLOW_CONTRACTS["4.7.1"] == (
        workflow_path,
        workflow_sha256,
        verifier_path,
        verifier_sha256,
    )
    with render_project_status._trusted_git_session(ROOT):
        release = render_project_status._git_bytes(
            ROOT,
            "show",
            "--end-of-options",
            f"{source_commit}:{workflow_path}",
        )

    assert hashlib.sha256(release).hexdigest() == workflow_sha256
    header = f"blob {len(release)}\0".encode("ascii")
    assert (
        hashlib.sha1(header + release, usedforsecurity=False).hexdigest()
        == workflow_blob_sha
    )
    text = release.decode("utf-8", "strict")
    assert text.count(f"actions/attest@{historical_attest}") == 2
    assert f"actions/attest@{reviewed_attest}" not in text


def test_trusted_dependency_inputs_are_codeowner_protected() -> None:
    codeowners = CODEOWNERS.read_text(encoding="utf-8")
    for path in (
        "/requirements/",
        "/tools/ci-vitest/",
        "/ops/ci/",
        "/ops/build_pyz.py",
        "/ops/generate_spdx_sbom.py",
        "/tests/test_action_security.py",
        "/tests/test_dependency_lock_policy.py",
        "/tests/test_release_security.py",
        "/tests/test_spdx_sbom.py",
        "/tests/schema/",
        "/tests/test_zipapp.py",
        "/docs/DEPENDENCY_POLICY.md",
        "/docs/EVIDENCE_BUNDLES.md",
        "/docs/GUARD.md",
        "/docs/SBOM.md",
    ):
        assert f"{path} @MANA-awam" in codeowners
