# ------------------------------------------------------------------------------
# Copyright © 2026 EvoRise Tech. All rights reserved.
# Author / original creator: Mana Alharbi.
# Licensor: EvoRise Tech.
# Source-available — see LICENSE for permitted use.
# ------------------------------------------------------------------------------
"""Typed stdlib-only owner for the public ``evo-guard init`` command."""

from __future__ import annotations

import argparse
from collections.abc import Callable
from dataclasses import dataclass
from typing import Protocol, TextIO


class _JoinPath(Protocol):
    def __call__(self, *parts: str) -> str: ...


class _MakeDirectories(Protocol):
    def __call__(self, path: str, *, exist_ok: bool = False) -> None: ...


class _OpenText(Protocol):
    def __call__(
        self,
        path: str,
        mode: str,
        *,
        encoding: str,
    ) -> TextIO: ...


class _DumpJson(Protocol):
    def __call__(
        self,
        value: object,
        handle: TextIO,
        *,
        indent: int,
    ) -> None: ...


@dataclass(frozen=True, slots=True)
class InitPathServices:
    """Live path operations used by policy-path inference."""

    absolute_path_provider: Callable[[], Callable[[str], str]]
    directory_name_provider: Callable[[], Callable[[str], str]]
    base_name_provider: Callable[[], Callable[[str], str]]
    join_path_provider: Callable[[], _JoinPath]
    current_directory_provider: Callable[[], Callable[[], str]]


@dataclass(frozen=True, slots=True)
class InitCommandServices:
    """Live compatibility seams for one initialization command."""

    validate_credential_key_provider: Callable[
        [],
        Callable[[object], str],
    ]
    render_public_workflow_provider: Callable[
        [],
        Callable[[str], str],
    ]
    render_advisory_workflow_provider: Callable[
        [],
        Callable[[str], str],
    ]
    render_private_workflow_provider: Callable[
        [],
        Callable[[str, str], str],
    ]
    default_policy_path_provider: Callable[
        [],
        Callable[[str], str],
    ]
    path_exists_provider: Callable[
        [],
        Callable[[str], bool],
    ]
    directory_name_provider: Callable[
        [],
        Callable[[str], str],
    ]
    make_directories_provider: Callable[[], _MakeDirectories]
    open_text_provider: Callable[[], _OpenText]
    dump_json_provider: Callable[[], _DumpJson]


def validate_github_actions_credential_key(
    value: object,
    *,
    credential_name_matches: Callable[[str], bool],
) -> str:
    """Validate one GitHub Actions secret name without accepting its value."""

    if not isinstance(value, str) or not credential_name_matches(value):
        raise ValueError(
            "--evoguard-token-secret must be a GitHub Actions credential name "
            "containing only letters, digits, and underscores"
        )
    if value.upper().startswith("GITHUB_"):
        raise ValueError("--evoguard-token-secret must not begin with GITHUB_")
    return value


def render_public_workflow(ref: str) -> str:
    """Render the public composite-Action workflow at one immutable ref."""

    return f"""\
# EvoGuard — generated by `evo-guard init`.
# Verifies each PR's source changes against the selected judge and REJECTS
# edits/deletions to paths protected by the target branch's base-owned policy.
# Judge settings are read from the target branch's .evoguard.json policy.
name: EvoGuard

on:
  pull_request:

permissions: {{}}

jobs:
  guard:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0            # Guard needs the base commit to diff against
          persist-credentials: false

      - uses: EvoRiseKsa/EvoOM-Guard-m@{ref}
        with:
          fail-on: "any-non-pass"   # or "rejected-only" to gate only reward-hacks
"""


def render_advisory_workflow(ref: str) -> str:
    """Render a read-only, evidence-preserving observation workflow.

    Guard still receives its fail-closed ``any-non-pass`` policy. The workflow
    converts only the step conclusion to success while an adopter evaluates the
    signal; the verdict JSON and Markdown report retain the actual decision.
    """

    return f"""\
# EvoGuard — generated by `evo-guard init --preset advisory`.
# ADVISORY ONLY: completed Guard verdicts do not block a PR in this workflow.
# Do not make this check required in branch protection while using this preset.
# Guard still runs fail-closed; continue-on-error changes only the step conclusion.
# Checkout, setup, Action crashes, or missing evidence can still fail the job.
name: EvoGuard observation

on:
  pull_request:

permissions: {{}}

jobs:
  observe:
    name: Observe EvoGuard evidence (non-blocking)
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run EvoGuard (preserve the actual verdict)
        id: guard
        continue-on-error: true
        uses: EvoRiseKsa/EvoOM-Guard-m@{ref}
        with:
          fail-on: "any-non-pass"   # Never weaken the Guard decision itself.
          comment: "false"          # Candidate execution receives no write token.

      - name: Upload EvoGuard observation evidence
        if: ${{{{ always() }}}}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: evoguard-observation-${{{{ github.run_id }}}}-${{{{ github.run_attempt }}}}
          path: |
            ${{{{ steps.guard.outputs.json-path }}}}
            ${{{{ steps.guard.outputs.report-path }}}}
          if-no-files-found: error
"""


def render_private_workflow(
    ref: str,
    credential_key: str = "EVOGUARD_TOKEN",
) -> str:
    """Refuse the historical secret-bearing private-PR scaffold."""

    del ref, credential_key
    raise ValueError(
        "--private-evoguard is disabled: a pull_request workflow controlled by "
        "the candidate cannot safely receive a private-repository credential, "
        "even in a separate job. Grant the repository access to a pinned private "
        "Action, or publish a prebuilt internal artifact from a separately "
        "protected workflow that never evaluates candidate-controlled YAML."
    )


def infer_default_policy_path(
    workflow_path: str,
    *,
    services: InitPathServices,
) -> str:
    """Infer the established repository policy path from a workflow path."""

    absolute_path = services.absolute_path_provider()
    absolute = absolute_path(workflow_path)
    directory_name = services.directory_name_provider()
    workflow_dir = directory_name(absolute)
    directory_name = services.directory_name_provider()
    github_dir = directory_name(workflow_dir)
    base_name = services.base_name_provider()
    if base_name(workflow_dir) == "workflows":
        base_name = services.base_name_provider()
        if base_name(github_dir) == ".github":
            join_path = services.join_path_provider()
            directory_name = services.directory_name_provider()
            return join_path(
                directory_name(github_dir),
                ".evoguard.json",
            )
    join_path = services.join_path_provider()
    policy_root = workflow_dir
    if not policy_root:
        current_directory = services.current_directory_provider()
        policy_root = current_directory()
    return join_path(policy_root, ".evoguard.json")


def _advisory_ref_supported(ref: str) -> bool:
    """Compare a validated SemVer tag without integer-conversion limits."""

    if not ref.startswith("v"):
        return True
    numeric_parts = tuple(
        part.lstrip("0") or "0" for part in ref[1:].split(".")
    )
    version_key = tuple((len(part), part) for part in numeric_parts)
    return version_key >= ((1, "4"), (1, "6"), (1, "0"))


def _select_workflow(
    args: argparse.Namespace,
    *,
    services: InitCommandServices,
    out: Callable[[str], None],
) -> tuple[str, str] | None:
    """Select and render one workflow while preserving live lookup order."""

    if getattr(args, "private_evoguard", False):
        try:
            validate_credential_key = services.validate_credential_key_provider()
            credential_key = validate_credential_key(
                getattr(args, "github_actions_credential_key", "EVOGUARD_TOKEN")
            )
            render_private_workflow = services.render_private_workflow_provider()
            return "blocking", render_private_workflow(args.ref, credential_key)
        except ValueError as exc:
            out(f"usage: {exc}")
            return None

    preset = getattr(args, "preset", "blocking")
    if preset == "blocking":
        render_public_workflow = services.render_public_workflow_provider()
        return preset, render_public_workflow(args.ref)
    if preset == "advisory":
        if not _advisory_ref_supported(args.ref):
            out(
                "usage: --preset advisory supports EvoGuard v4.6.0 or later "
                "tags as its reviewed Action-output contract; use a reviewed "
                "full commit SHA for unreleased source"
            )
            return None
        render_advisory_workflow = services.render_advisory_workflow_provider()
        return preset, render_advisory_workflow(args.ref)
    out("usage: --preset must be blocking or advisory")
    return None


def execute_init_command(
    args: argparse.Namespace,
    *,
    services: InitCommandServices,
    out: Callable[[str], None] = print,
) -> int:
    """Execute one already-parsed initialization command."""

    selected = _select_workflow(args, services=services, out=out)
    if selected is None:
        return 2
    preset, content = selected
    if args.stdout:
        out(content)
        return 0
    path = args.path
    path_exists = services.path_exists_provider()
    if path_exists(path) and not args.force:
        out(f"refusing to overwrite existing {path} — pass --force to replace it")
        return 1
    directory_name = services.directory_name_provider()
    parent = directory_name(path)
    if parent:
        make_directories = services.make_directories_provider()
        make_directories(parent, exist_ok=True)
    open_text = services.open_text_provider()
    with open_text(path, "w", encoding="utf-8") as handle:
        handle.write(content)
    policy_path = args.policy_path
    if not policy_path:
        default_policy_path = services.default_policy_path_provider()
        policy_path = default_policy_path(path)
    path_exists = services.path_exists_provider()
    if path_exists(policy_path):
        out(f"kept existing trusted policy {policy_path}")
    else:
        directory_name = services.directory_name_provider()
        policy_parent = directory_name(policy_path)
        if policy_parent:
            make_directories = services.make_directories_provider()
            make_directories(policy_parent, exist_ok=True)
        open_text = services.open_text_provider()
        with open_text(
            policy_path,
            "w",
            encoding="utf-8",
        ) as handle:
            dump_json = services.dump_json_provider()
            dump_json(
                {"test_command": args.test_command},
                handle,
                indent=2,
            )
            handle.write("\n")
        out(f"wrote {policy_path}")
    out(f"wrote {path}")
    if preset == "advisory":
        out(
            "next: commit it and open a PR — completed non-PASS verdicts remain "
            "visible in the summary and uploaded evidence without blocking. "
            "Checkout, setup, Action crashes, or missing evidence can still fail "
            "the job. Do not make this check required: doing so admits completed "
            "non-PASS verdicts by design. Promote by rerunning `evo-guard init` "
            "with --preset blocking --force while preserving these exact values: "
            f"ref=[{args.ref}], workflow path=[{path}], trusted policy "
            f"path=[{policy_path}]."
        )
    else:
        out(
            "next: commit it and open a PR — EvoGuard writes the verdict to the job "
            "summary and fails the check on anything but PASS. Edit .evoguard.json "
            "to change the trusted judge policy."
        )
    return 0


__all__ = [
    "InitCommandServices",
    "InitPathServices",
    "execute_init_command",
    "infer_default_policy_path",
    "render_advisory_workflow",
    "render_private_workflow",
    "render_public_workflow",
    "validate_github_actions_credential_key",
]
