# ------------------------------------------------------------------------------
# Copyright © 2026 EvoRise Tech. All rights reserved.
# Author / original creator: Mana Alharbi.
# Licensor: EvoRise Tech.
# Source-available — see LICENSE for permitted use.
# ------------------------------------------------------------------------------
"""Typed stdlib-only owner for the public ``evo-guard init`` command."""

from __future__ import annotations

import argparse
from collections.abc import Callable
from dataclasses import dataclass
from typing import Protocol, TextIO


class _JoinPath(Protocol):
    def __call__(self, *parts: str) -> str: ...


class _MakeDirectories(Protocol):
    def __call__(self, path: str, *, exist_ok: bool = False) -> None: ...


class _OpenText(Protocol):
    def __call__(
        self,
        path: str,
        mode: str,
        *,
        encoding: str,
    ) -> TextIO: ...


class _DumpJson(Protocol):
    def __call__(
        self,
        value: object,
        handle: TextIO,
        *,
        indent: int,
    ) -> None: ...


@dataclass(frozen=True, slots=True)
class InitPathServices:
    """Live path operations used by policy-path inference."""

    absolute_path_provider: Callable[[], Callable[[str], str]]
    directory_name_provider: Callable[[], Callable[[str], str]]
    base_name_provider: Callable[[], Callable[[str], str]]
    join_path_provider: Callable[[], _JoinPath]
    current_directory_provider: Callable[[], Callable[[], str]]


@dataclass(frozen=True, slots=True)
class InitCommandServices:
    """Live compatibility seams for one initialization command."""

    validate_credential_key_provider: Callable[
        [],
        Callable[[object], str],
    ]
    render_public_workflow_provider: Callable[
        [],
        Callable[[str], str],
    ]
    render_private_workflow_provider: Callable[
        [],
        Callable[[str, str], str],
    ]
    default_policy_path_provider: Callable[
        [],
        Callable[[str], str],
    ]
    path_exists_provider: Callable[
        [],
        Callable[[str], bool],
    ]
    directory_name_provider: Callable[
        [],
        Callable[[str], str],
    ]
    make_directories_provider: Callable[[], _MakeDirectories]
    open_text_provider: Callable[[], _OpenText]
    dump_json_provider: Callable[[], _DumpJson]


def validate_github_actions_credential_key(
    value: object,
    *,
    credential_name_matches: Callable[[str], bool],
) -> str:
    """Validate one GitHub Actions secret name without accepting its value."""

    if not isinstance(value, str) or not credential_name_matches(value):
        raise ValueError(
            "--evoguard-token-secret must be a GitHub Actions credential name "
            "containing only letters, digits, and underscores"
        )
    if value.upper().startswith("GITHUB_"):
        raise ValueError("--evoguard-token-secret must not begin with GITHUB_")
    return value


def render_public_workflow(ref: str) -> str:
    """Render the public composite-Action workflow at one immutable ref."""

    return f"""\
# EvoGuard — generated by `evo-guard init`.
# Verifies each PR's source changes against the repo's own tests and REJECTS any
# edit to the tests or their configuration (an AI-patch reward-hack gate).
# Judge settings are read from the target branch's .evoguard.json policy.
name: EvoGuard

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write   # required to post the verdict as a PR comment

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0            # Guard needs the base commit to diff against

      - uses: EvoRiseKsa/EvoOM-Guard-m@{ref}
        with:
          comment: "true"           # same-repo PR comment; forks keep the job summary
          fail-on: "any-non-pass"   # or "rejected-only" to gate only reward-hacks
"""


def render_private_workflow(
    ref: str,
    credential_key: str = "EVOGUARD_TOKEN",
) -> str:
    """Render the private-repository pip workflow at one immutable ref."""

    return f"""\
# EvoGuard — generated by `evo-guard init --private-evoguard`.
# EvoGuard is installed from a private GitHub repo via pip.
# Judge settings are read from the target branch's .evoguard.json policy.
# Add a PAT with read access to the EvoGuard repo as the {credential_key} secret:
#   Settings -> Secrets and variables -> Actions -> New repository secret
name: EvoGuard

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write   # required to post the verdict as a PR comment

jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          fetch-depth: 0            # Guard needs the base commit to diff against

      - name: Install EvoGuard
        env:
          {credential_key}: ${{{{ secrets.{credential_key} }}}}
        run: pip install "git+https://x-access-token:${{{credential_key}}}@github.com/EvoRiseKsa/EvoOM-Guard-m.git@{ref}"

      - name: Run EvoGuard
        run: |
          # Materialize policy from the event's base commit, never from the PR head.
          BASE="${{{{ github.event.pull_request.base.sha }}}}"
          git rev-parse --verify --quiet "$BASE^{{commit}}" >/dev/null
          BASE_POLICY_CONFIG="$RUNNER_TEMP/evoguard-base-policy.json"
          if git cat-file -e "$BASE:.evoguard.json" 2>/dev/null; then
            git show "$BASE:.evoguard.json" > "$BASE_POLICY_CONFIG"
          else
            printf '{{}}\\n' > "$BASE_POLICY_CONFIG"
          fi
          git diff "$BASE...HEAD" | \\
            evo-guard guard . --diff - --config "$BASE_POLICY_CONFIG" \\
            --report evoguard.md --json evoguard.json
          cat evoguard.md >> "$GITHUB_STEP_SUMMARY"

      - name: Post verdict as PR comment
        if: ${{{{ always() && github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.user.login != 'dependabot[bot]' }}}}
        continue-on-error: true
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        with:
          script: |
            const fs = require('fs');
            const report = fs.existsSync('evoguard.md')
              ? fs.readFileSync('evoguard.md', 'utf8')
              : '_EvoGuard did not produce a report._';
            await github.rest.issues.createComment({{
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: report,
            }});
"""


def infer_default_policy_path(
    workflow_path: str,
    *,
    services: InitPathServices,
) -> str:
    """Infer the established repository policy path from a workflow path."""

    absolute_path = services.absolute_path_provider()
    absolute = absolute_path(workflow_path)
    directory_name = services.directory_name_provider()
    workflow_dir = directory_name(absolute)
    directory_name = services.directory_name_provider()
    github_dir = directory_name(workflow_dir)
    base_name = services.base_name_provider()
    if base_name(workflow_dir) == "workflows":
        base_name = services.base_name_provider()
        if base_name(github_dir) == ".github":
            join_path = services.join_path_provider()
            directory_name = services.directory_name_provider()
            return join_path(
                directory_name(github_dir),
                ".evoguard.json",
            )
    join_path = services.join_path_provider()
    policy_root = workflow_dir
    if not policy_root:
        current_directory = services.current_directory_provider()
        policy_root = current_directory()
    return join_path(policy_root, ".evoguard.json")


def execute_init_command(
    args: argparse.Namespace,
    *,
    services: InitCommandServices,
    out: Callable[[str], None] = print,
) -> int:
    """Execute one already-parsed initialization command."""

    if getattr(args, "private_evoguard", False):
        try:
            validate_credential_key = services.validate_credential_key_provider()
            credential_key = validate_credential_key(
                getattr(
                    args,
                    "github_actions_credential_key",
                    "EVOGUARD_TOKEN",
                )
            )
        except ValueError as exc:
            out(f"usage: {exc}")
            return 2
        render_private_workflow = services.render_private_workflow_provider()
        content = render_private_workflow(args.ref, credential_key)
    else:
        render_public_workflow = services.render_public_workflow_provider()
        content = render_public_workflow(args.ref)
    if args.stdout:
        out(content)
        return 0
    path = args.path
    path_exists = services.path_exists_provider()
    if path_exists(path) and not args.force:
        out(f"refusing to overwrite existing {path} — pass --force to replace it")
        return 1
    directory_name = services.directory_name_provider()
    parent = directory_name(path)
    if parent:
        make_directories = services.make_directories_provider()
        make_directories(parent, exist_ok=True)
    open_text = services.open_text_provider()
    with open_text(path, "w", encoding="utf-8") as handle:
        handle.write(content)
    policy_path = args.policy_path
    if not policy_path:
        default_policy_path = services.default_policy_path_provider()
        policy_path = default_policy_path(path)
    path_exists = services.path_exists_provider()
    if path_exists(policy_path):
        out(f"kept existing trusted policy {policy_path}")
    else:
        directory_name = services.directory_name_provider()
        policy_parent = directory_name(policy_path)
        if policy_parent:
            make_directories = services.make_directories_provider()
            make_directories(policy_parent, exist_ok=True)
        open_text = services.open_text_provider()
        with open_text(
            policy_path,
            "w",
            encoding="utf-8",
        ) as handle:
            dump_json = services.dump_json_provider()
            dump_json(
                {"test_command": args.test_command},
                handle,
                indent=2,
            )
            handle.write("\n")
        out(f"wrote {policy_path}")
    out(f"wrote {path}")
    out(
        "next: commit it and open a PR — EvoGuard posts a verdict and fails the "
        "check on anything but PASS. Edit .evoguard.json to change the trusted judge policy."
    )
    return 0


__all__ = [
    "InitCommandServices",
    "InitPathServices",
    "execute_init_command",
    "infer_default_policy_path",
    "render_private_workflow",
    "render_public_workflow",
    "validate_github_actions_credential_key",
]
